export const STAKEHOLDER_NAME_MAX_CHARS = 120;
export const STAKEHOLDER_ROLE_MAX_CHARS = 120;
export const STAKEHOLDER_IMPACT_AREA_MAX_CHARS = 200;
export const STAKEHOLDER_NOTES_MAX_CHARS = 200;
export const STAKEHOLDER_SYSTEM_DESCRIPTION_MAX_CHARS = 200;
